import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { TabsProvider } from "../components/context/TabsContext";
import HideTopbarOnAuth from "../components/HideTopbarOnAuth";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "BrainLink AI",
  description: "Generated by create next app",
  icons: {
    icon: [
      { url: "/brainlink.svg", type: "image/svg+xml" },
    ],
  },
};


interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased pt-16`}>
        <TabsProvider>
          <HideTopbarOnAuth>{children}</HideTopbarOnAuth>
        </TabsProvider>
      </body>
    </html>
  );
}


